### ISSUE TITLE
Can't use python utilities on windows 10......

### ISSUE THREAD

**Issue by shreechandansamal** [MrBlinky/Arduboy-Python-Utilities#2]
Sir I am noob in programming.....and also in electronic....so please help me sir
I have a windows 10 laptop.. according to the python utilities....i do the below steps
    1.install python 3.7
    2.install PySerial (through command prompt using command line (python -m pip install pyserial))
    3.But due to lack of knowledge i  can't understand what this is written >>>    (Double click the uploader-create-send-to-shortcut.vbs for right click Send to upload option(Windows only)
    
 ...........sir what to do here, i can't understand

4.Then when i do this on my command prompt >>

  Microsoft Windows [Version 10.0.19042.746]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\chandan>cd C:\Users\chandan\OneDrive\Desktop\Arduboy-Python-Utilities-master

C:\Users\chandan\OneDrive\Desktop\Arduboy-Python-Utilities-master>uploader.py

   then always i got this error massage >>
   
   C:\Users\chandan\OneDrive\Desktop\Arduboy-Python-Utilities-master>
[main 2021-01-28T00:03:42.880Z] update#setState idle
(node:820) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\chandan\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-sqlite3\build\Release\sqlite.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:820) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\chandan\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:7224) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\chandan\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
[main 2021-01-28T00:04:12.884Z] update#setState checking for updates
[main 2021-01-28T00:04:13.116Z] update#setState idle

   please suggest me where am i incorrect (i think i have to add here the COM port but no idea how to add it ) and what thing i have to do .....
how to upload the hex file using python....in windows..(please explain it step by step....)
😥😥😥😥😔😔😔😭😭please help me...

**Comment by MrBlinky** [comment]
Hi,

 

It seems that .py files are not assosiated with python. You should change the file assosiation (Right click  > open with, always use this program)

so .py files are opend with Python.

 

Van: shreechandan samal [mailto:notifications@github.com] 
Verzonden: donderdag 28 januari 2021 02:34
Aan: MrBlinky/Arduboy-Python-Utilities
CC: Subscribed
Onderwerp: [MrBlinky/Arduboy-Python-Utilities] Can't use python utilities on windows 10...... (#2)

 

     Sir I am noob in programming.....and also in electronic....so please help me sir
 

I have a windows 10 laptop.. according to the python utilities....i do the below steps
1.install python 3.7
2.install PySerial (through command prompt using command line (python -m pip install pyserial))
3.But due to lack of knowledge i can't understand what this is written >>> (Double click the uploader-create-send-to-shortcut.vbs for right click Send to upload option(Windows only)

...........sir what to do here, i can't understand

4.Then when i do this on my command prompt >>

Microsoft Windows [Version 10.0.19042.746]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\chandan>cd C:\Users\chandan\OneDrive\Desktop\Arduboy-Python-Utilities-master

C:\Users\chandan\OneDrive\Desktop\Arduboy-Python-Utilities-master>uploader.py

then always i got this error massage >>

C:\Users\chandan\OneDrive\Desktop\Arduboy-Python-Utilities-master>
[main 2021-01-28T00:03:42.880Z] update#setState idle
(node:820) Electron: Loading non-context-aware native module in renderer: '\?\C:\Users\chandan\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-sqlite3\build\Release\sqlite.node'. This is deprecated, see electron/electron#18397 <https://github.com/electron/electron/issues/18397> .
(node:820) Electron: Loading non-context-aware native module in renderer: '\?\C:\Users\chandan\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see electron/electron#18397 <https://github.com/electron/electron/issues/18397> .
(node:7224) Electron: Loading non-context-aware native module in renderer: '\?\C:\Users\chandan\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see electron/electron#18397 <https://github.com/electron/electron/issues/18397> .
[main 2021-01-28T00:04:12.884Z] update#setState checking for updates
[main 2021-01-28T00:04:13.116Z] update#setState idle

please suggest me where am i incorrect (i think i have to add here the COM port but no idea how to add it ) and what thing i have to do .....
how to upload the hex file using python....in windows..(please explain it step by step....)
😥😥😥😥😔😔😔😭😭please help me...

**Comment by shreechandansamal** [comment]
Thank you for replying 🙂
I can't understand what you are saying 😞..
   When I use the command line uploader.py.... it always show me that error which I have shown you...
  And always open the VS code(visual studio)..... How to do it working..
I can't do anything.. please reply me with some pictures or more explanation then I shall grateful to you... please..

**Comment by shreechandansamal** [comment]
Please show me how can I upload the .hex file in Windows system..
 If you explain me in video or picture format it will be much easier to understand....Thank you sir...(should I have to uninstall the python???)..
I have no experience in python please help me...🥺🥺🥺❤️

**Comment by shreechandansamal** [comment]
Ok Thank you sir❤️ I rectify my problem  >>In my pc it is always opens with Vs code...but when I tried on other computer I will successfully do it ...
Please tell me how to disable it (Opens with) means how to do it opens with .py 
Please share with me..
Thanks 😊

**Comment by shreechandansamal** [comment]
Please reply me back.

**Comment by MrBlinky** [comment]
Check this out:

 

https://helpdeskgeek.com/how-to/how-to-change-the-default-program-to-open-a-file-with/

 

 

Van: shreechandan samal [mailto:notifications@github.com] 
Verzonden: vrijdag 29 januari 2021 02:01
Aan: MrBlinky/Arduboy-Python-Utilities
CC: Mr.Blinky; Comment
Onderwerp: Re: [MrBlinky/Arduboy-Python-Utilities] Can't use python utilities on windows 10...... (#2)

 

Please reply me back.

**Comment by shreechandansamal** [comment]
Yes I do it thank you so much.. ❤️😊
Now I am making home made arduboy with serial flash (standard wiring)...
But I always found only the usb boot logo on my display...
When I write then it show me some time the chip availability..
Sometimes it show me there is no serial chip ...
But In both case I always found the usb boot logo in my display .... What to do now... please say me...
I am a arduboy lover..,..

**Comment by MrBlinky** [comment]
Check your wiring. For further issues with your home made Arduboy. Please use the Arduboy community https://community.arduboy.com/
